# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('commitment', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('min_grade', models.DecimalField(decimal_places=2, max_digits=2)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_created_by',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Course_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('status_date', models.DateField()),
                ('final_grade', models.DecimalField(decimal_places=2, max_digits=2)),
                ('certificate_ID', models.TextField(max_length=20)),
                ('certificate_location', models.TextField(max_length=20)),
                ('course_session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course_session')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=15)),
                ('institution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_no', models.IntegerField()),
                ('material_link', models.TextField()),
                ('mandatory', models.BooleanField()),
                ('max_points', models.IntegerField()),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Material_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='On_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
                ('lecturer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(default='India', max_length=20)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('country', models.CharField(default='India', max_length=20)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('profile_image', models.FileField(default='abc/def.jpg', upload_to='imgs')),
                ('conditions', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField()),
                ('attempt_link', models.TextField()),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('enrolled_course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Enrolled_course')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Material')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='material_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Material_type'),
        ),
        migrations.AddField(
            model_name='enrolled_course',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Status'),
        ),
        migrations.AddField(
            model_name='enrolled_course',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Student'),
        ),
        migrations.AddField(
            model_name='course_created_by',
            name='lecturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Lecturer'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course'),
        ),
    ]
