# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20170313_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=130),
        ),
    ]
