# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_auto_20170313_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='institution_id',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='title',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='conditions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='country',
            field=models.CharField(default='India', max_length=20),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='email',
            field=models.CharField(default='India', max_length=40),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='password',
            field=models.CharField(default='password', max_length=130),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='profile_image',
            field=models.ImageField(default='cms/profile_pics/dummy.jpg', upload_to='cms/profile_pics/'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='user_name',
            field=models.CharField(default='user_name', max_length=10),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='lms/profile_pics/dummy.jpg', upload_to='lms/profile_pics/'),
        ),
    ]
