# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20170418_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_banner',
            field=models.ImageField(default='cms/course_banner/dummy.jpg', upload_to='cms/course_banner/'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_icon',
            field=models.ImageField(default='cms/course_icon/dummy.jpg', upload_to='cms/course_icon/'),
        ),
    ]
