# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_auto_20170424_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='commitment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_price',
        ),
        migrations.AddField(
            model_name='course',
            name='course_category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
