# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_auto_20170425_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_schedules',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='min_grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
