# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_auto_20170426_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('material_link', models.TextField(null=True)),
                ('material_text', models.TextField(null=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='material',
            name='chapter_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_no',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_type_id',
        ),
        migrations.RemoveField(
            model_name='material',
            name='max_points',
        ),
        migrations.AddField(
            model_name='material',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Course'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='week',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_link',
            field=models.TextField(null=True),
        ),
    ]
