# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20170426_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignments',
            old_name='material_link',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='material_text',
            new_name='q10',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='week',
        ),
        migrations.AddField(
            model_name='assignments',
            name='a1',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a10',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a2',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a3',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a4',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a5',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a6',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a7',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a8',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='a9',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q6',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q7',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q8',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='q9',
            field=models.TextField(null=True),
        ),
    ]
