# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_auto_20170426_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Course'),
        ),
        migrations.AddField(
            model_name='assignments',
            name='week',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
