# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_auto_20170426_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolled_course',
            name='certificate_ID',
        ),
        migrations.RemoveField(
            model_name='enrolled_course',
            name='certificate_location',
        ),
        migrations.RemoveField(
            model_name='enrolled_course',
            name='final_grade',
        ),
        migrations.RemoveField(
            model_name='enrolled_course',
            name='status_date',
        ),
        migrations.RemoveField(
            model_name='enrolled_course',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='student_results',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='student_results',
            name='attempt_link',
        ),
        migrations.RemoveField(
            model_name='student_results',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='student_results',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='student_results',
            name='started',
        ),
        migrations.AddField(
            model_name='enrolled_course',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='student_results',
            name='assignment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Assignments'),
        ),
        migrations.AlterField(
            model_name='enrolled_course',
            name='course_session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course'),
        ),
        migrations.AlterField(
            model_name='student_results',
            name='enrolled_course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Enrolled_course'),
        ),
    ]
